//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:sql.example.com;Initial Catalog=example;" +
            "User ID=example_user;Password=REDACTED;")]
        public string Connection {
            get {
                return ((string)(this["Connection"]));
            }
            set {
                this["Connection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT DISTINCT p.UPI, 
                ISNULL(p.Name, '') AS Name, 
                ISNULL(b.Name, '') AS Brand, 
                ISNULL(p.Price, 0.0) AS Price, 
                ISNULL(p.RecommendedPrice, 0.0) AS RecommendedPrice, 
                CASE  
                    WHEN CAST (pc2.EndDate AS date) < GETDATE() THEN CAST(0.0 As Decimal)
                    ELSE ISNULL(pc2.Price, CAST(0.0 As Decimal))
                END AS CatalogPrice, 
                ISNULL(pc2.EndDate,'') AS CatEndDate, 
                ISNULL(c.Name, '') AS ParentCategory, 
                ISNULL(i.Name, '') AS ActiveIngredient, 
                ISNULL(p.ShelfTalker, 0) AS ShelfTalker
FROM            Product AS p 
LEFT OUTER JOIN Brand AS b ON p.BrandID = b.ID 
LEFT OUTER JOIN ProductCategory AS pc ON p.ID = pc.ProductID 
LEFT OUTER JOIN Category AS c ON c.ID = pc.CategoryID 
LEFT OUTER JOIN Ingredient AS i ON p.IngredientID = i.ID 
LEFT OUTER JOIN ProductCatalog AS pc2 ON pc2.ProductID = p.ID 
LEFT OUTER JOIN Catalog AS c2 ON c2.RPMID = pc2.CatalogID 
group by p.UPI, p.Name, b.name, p.Price, p.RecommendedPrice, pc2.Price, pc2.EndDate, c.Name, i.name, p.ShelfTalker, c2.RPMID
HAVING c2.RPMID = MAX(c2.RPMID) OR c2.RPMID IS NULL 
ORDER BY p.UPI")]
        public string Query {
            get {
                return ((string)(this["Query"]));
            }
            set {
                this["Query"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Products.xml")]
        public string Output {
            get {
                return ((string)(this["Output"]));
            }
            set {
                this["Output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data/Shelftalkers")]
        public string FTPLocation {
            get {
                return ((string)(this["FTPLocation"]));
            }
            set {
                this["FTPLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("user|example")]
        public string FTPUsername {
            get {
                return ((string)(this["FTPUsername"]));
            }
            set {
                this["FTPUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("REDACTED")]
        public string FTPPassword {
            get {
                return ((string)(this["FTPPassword"]));
            }
            set {
                this["FTPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp.example.com")]
        public string FTPHost {
            get {
                return ((string)(this["FTPHost"]));
            }
            set {
                this["FTPHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string LocalFolder {
            get {
                return ((string)(this["LocalFolder"]));
            }
            set {
                this["LocalFolder"] = value;
            }
        }
    }
}
